import Vue from 'vue';

Vue.component('btn', require('../modules/btn.vue'));
Vue.component('ktable', require('../modules/table.vue'));
Vue.component('tablerow', require('../modules/tablerow.vue'));
Vue.component('tablecell', require('../modules/tablecell.vue'));
Vue.component('tableheading', require('../modules/tableheading.vue'));
Vue.component('progressbar', require('../modules/progressbar.vue'));
Vue.component('searchbox', require('../modules/searchbox.vue'));
Vue.component('switcher', require('../modules/switcher.vue'));
Vue.component('switchbtn', require('../modules/switch.vue'));
Vue.component('card', require('../modules/card.vue'));
Vue.component('textfield', require('../modules/textfield.vue'));
Vue.component('colorfield', require('../modules/colorfield.vue'));
Vue.component('urlfield', require('../modules/urlfield.vue'));
Vue.component('filefield', require('../modules/filefield.vue'));
Vue.component('imagefield', require('../modules/imagefield.vue'));
Vue.component('wysiwyg', require('../modules/wysiwyg.vue'));
Vue.component('repeater', require('../modules/repeater.vue'));
Vue.component('genericfield', require('../modules/genericfield.vue'));
Vue.component('checkboxfield', require('../modules/checkboxfield.vue'));
Vue.component('radiofield', require('../modules/radiofield.vue'));
Vue.component('groupfield', require('../modules/groupfield.vue'));